/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ostatni;

import grafobjekty.HerniPanel;
import java.awt.Container;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setPreferredSize(new Dimension(400, 300));
        this.setSize(new Dimension(400,300));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        scoreboard = new javax.swing.JButton();
        initGame = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, 40));

        scoreboard.setText("Scoreboard");
        add(scoreboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 40));

        initGame.setText("Start");
        initGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initGameActionPerformed(evt);
            }
        });
        add(initGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void initGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initGameActionPerformed
        System.out.println("Musim to vyresit.");
        JFrame frame = new JFrame();
        frame.setTitle("Slav Squat");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.add(new HerniPanel(javax.swing.SwingUtilities.getWindowAncestor(Menu.this), JOptionPane.showInputDialog(this, "Enter nickname")));
        frame.pack();
        frame.setVisible(true);
        javax.swing.SwingUtilities.getWindowAncestor(Menu.this).setVisible(false);
    }//GEN-LAST:event_initGameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton initGame;
    private javax.swing.JButton scoreboard;
    // End of variables declaration//GEN-END:variables

}
